#!/usr/bin/env python3
"""Regenerate build-time syntax colors after upgrading Hugo."""
from pathlib import Path
import re
import subprocess


def stylesheet(style):
    css = subprocess.check_output(['hugo', 'gen', 'chromastyles', '--style', style], text=True)
    return re.sub(r'/\*.*?\*/\s*', '', css).strip()


def scoped(css, parent):
    rules = []
    for line in css.splitlines():
        selector, declarations = line.split('{', 1)
        selectors = ', '.join(f'{parent} {part.strip()}' for part in selector.split(','))
        rules.append(f'{selectors} {{{declarations}')
    return '\n'.join(rules)


light = stylesheet('github')
dark = stylesheet('github-dark')
output = '/* Generated by scripts/syntax.py. */\n' + light + '\n'
output += scoped(dark, ':root[data-theme="dark"]') + '\n'
output += '@media (prefers-color-scheme: dark) {\n'
output += scoped(dark, ':root:not([data-theme="light"])') + '\n}\n'
(Path(__file__).resolve().parents[1] / 'assets/css/syntax.css').write_text(output)
